#! /bin/bash

cd src

if test ! -e bjam
then {
    echo Create build tools
    cd tools/jam
    ./build_dist.sh
    if test -e ./src/bin.linuxx86_64/bjam
    then {
        cp -v ./src/bin.linuxx86_64/bjam ../..
    } else {
        cp -v ./src/bin.linuxx86/bjam ../..
    }
    fi
    cd ../..
    ./configure
    cp bjam ..
}
fi

../compile

cd ..
