#! /bin/bash
cd `dirname $0`

if test -z $1
then {
    export MAJOR=41
} else {
    export MAJOR=$1
}
fi

if test -z $2
then {
    export MINOR=0
} else {
    export MINOR=$2
}
fi

export VERSION=1_$MAJOR\_$MINOR
echo Using Boost_$VERSION

if test ! -e $VERSION
then {
    svn co http://svn.boost.org/svn/boost/tags/release/Boost_$VERSION $VERSION
}
fi

if test -e gcc.jam.$VERSION.darwin
then {
    cp -v gcc.jam.$VERSION.darwin $VERSION/tools/build/v2/tools/gcc.jam
}
fi

cd $VERSION

if test ! -e bjam
then {
    echo Create build tools
    cd tools/jam
    ./build_dist.sh
    cp -v `ls -d stage/bin.*`/bjam ../..
    cd ../..
}
fi

../compile $MAJOR $MINOR
if test -z $1
then {
    cd ..
    ./install $MAJOR $MINOR
}
fi

