#! /bin/bash
cd `dirname $0`

if test -z $1
then {
    export MAJOR=37
} else {
    export MAJOR=$1
}
fi

if test -z $2
then {
    export MINOR=0
} else {
    export MINOR=$2
}
fi

export VERSION=1_$MAJOR\_$MINOR
echo Using Boost_$VERSION

if test ! -e $VERSION
then {
    svn co http://svn.boost.org/svn/boost/tags/release/Boost_$VERSION $VERSION
}
fi

cd $VERSION

if test ! -e bjam
then {
    echo Create build tools
    cd tools/jam
    ./build_dist.sh
    if test -e stage/bin.linuxx86_64/bjam
    then {
        cp -v stage/bin.linuxx86_64/bjam ../..
    } else {
        if test -e stage/bin.macosxx86/bjam
	then {
	    cp -v stage/bin.macosxx86/bjam ../..
	}
        else {
            cp -v stage/bin.linuxx86/bjam ../..
        }
        fi
    }
    fi
    cd ../..
}
fi

../compile $VERSION
cd ..
./install $MAJOR $MINOR
