#! /bin/bash
set -e

OPTIONS="install cxxflags=-std=c++14 --layout=versioned --without-mpi --prefix=$(pwd)/../boost"

if test -e /proc/
then {
    export CPUCOUNT=$(grep -c ^processor /proc/cpuinfo)
    time ./bjam -j$CPUCOUNT toolset=gcc debug link=shared $OPTIONS \
        && time ./bjam -j$CPUCOUNT toolset=gcc release link=shared $OPTIONS
    [ $(which clang++) ] \
        && time ./bjam -j$CPUCOUNT toolset=clang debug link=shared $OPTIONS \
        && time ./bjam -j$CPUCOUNT toolset=clang release link=shared $OPTIONS
}
else {
    export CPUCOUNT=`sysctl -n hw.ncpu`
    time ./bjam -j$CPUCOUNT toolset=darwin architecture=x86 address-model=32_64 pch=off debug release $OPTIONS
}
fi
