#! /bin/bash

if test -e /proc/
then {
#    ./bjam -j`grep -c ^processor /proc/cpuinfo` --toolset=gcc tools --without-mpi --prefix=../boost
    ./bjam -j`grep -c ^processor /proc/cpuinfo` --toolset=gcc debug link=shared install --without-mpi --prefix=`pwd`/../boost \
    && ./bjam -j`grep -c ^processor /proc/cpuinfo` --toolset=gcc release link=shared install --without-mpi --prefix=`pwd`/../boost
}
else {
#    ./bjam toolset=darwin tools --without-mpi --prefix=../boost
    ./bjam toolset=darwin debug release install --without-mpi --prefix=`pwd`/../boost
}
fi
