#! /bin/bash

cp -v $1\_$2/bjam ..

echo Making ../boost-build.jam
rm ../boost-build.jam
echo BOOST_ROOT = \$\(.boost-build-file:D\) \;>>../boost-build.jam
echo BOOST_BUILD = \[ MATCH --boost-build=\(.*\) : \$\(ARGV\) \] \;>>../boost-build.jam
echo BOOST_BUILD ?= Boost/$1_$2/tools/build/v2 \;>>../boost-build.jam
echo boost-build \$\(BOOST_BUILD\) \;>>../boost-build.jam
