#! /bin/bash
cd `dirname $0`

if [[ "$1" == "lucid" || "$1" == "oneiric" || "$1" == "precise" || "$1" == "quantal" || "$1" == "raring" ]]
then {
    if [[ "$1" == "quantal" || "$1" == "raring" ]]
    then {
        BOOST_MAJOR=49
    }
    elif [[ "$1" == "oneiric" || "$1" == "precise" ]]
    then {
         BOOST_MAJOR=46
    }
    elif [ "$1" == "lucid" ]
    then {
        BOOST_MAJOR=40
    }
    fi

    echo Removing boost-build.jam
    rm -f ../boost-build.jam

    echo Making boost-version.jam
    echo BUILD_DIRECTORY = \"../build.tmp/$1\" \;>../boost-version.jam
    echo BOOST_VERSION_MAJOR = \"$BOOST_MAJOR\" \;>> ../boost-version.jam

    echo Creating local bjam
    echo \#\!/bin/bash>../bjam
    echo `which bjam` \$\*>>../bjam
    chmod +x ../bjam

    echo Creating target preservation script
    echo echo --preserve-test-targets > ../python.opts.sh
    chmod +x ../python.opts.sh

    JAMROOT=Jamroot.$1
}
else {
    rm ../bjam
    cp -v 1_$1\_$2/bjam ..

    echo Making boost-build.jam
    rm -f ../boost-build.jam
    echo BOOST_ROOT = \$\(.boost-build-file:D\) \;>>../boost-build.jam
    echo BOOST_BUILD = \[ MATCH --boost-build=\(.*\) : \$\(ARGV\) \] \;>>../boost-build.jam
    echo BOOST_BUILD ?= Boost/1_$1_$2/tools/build/v2 \;>>../boost-build.jam
    echo boost-build \$\(BOOST_BUILD\) \;>>../boost-build.jam

    echo Making boost-version.jam
    rm -f ../boost-version.jam
    echo BOOST_VERSION_MAJOR = \"$1\" \;>> ../boost-version.jam
    echo BOOST_VERSION_MINOR = \"$2\" \;>> ../boost-version.jam
    echo BOOST_HEADERS = \"../Boost/boost/include/boost-1_\$\(BOOST_VERSION_MAJOR\)/\" \;>> ../boost-version.jam
    echo BUILD_DIRECTORY = \"../build.tmp/1_$1_$2\" \;>> ../boost-version.jam

    echo Creating target preservation script
    if test $1 -lt 38
    then {
        echo echo --preserve-test-targets > ../python.opts.sh
    } else {
        echo echo preserve-test-targets=on > ../python.opts.sh
    }
    fi
    chmod +x ../python.opts.sh

    JAMROOT=Jamroot.ownbuild-versioned-layout
}
fi
echo Using $JAMROOT
cp $JAMROOT Jamroot

echo Installing colorbb
colorbb/use_colorbb
