#!/bin/bash
cd `dirname $0`

BOOST_VERSION=${1:-1_42_0}
IPHONE_VERSION=${2:-3.2}

rm boost-iphone-debug boost-iphone-release boost-iphonesim-debug boost-iphonesim-release
ln -sv boost${BOOST_VERSION}-iphone${IPHONE_VERSION}-debug boost-iphone-debug
ln -sv boost${BOOST_VERSION}-iphone${IPHONE_VERSION}-release boost-iphone-release
ln -sv boost${BOOST_VERSION}-iphonesim${IPHONE_VERSION}-debug boost-iphonesim-debug
ln -sv boost${BOOST_VERSION}-iphonesim${IPHONE_VERSION}-release boost-iphonesim-release
