#! /bin/bash
cd `dirname $0`

export VERSION=1_42_0
echo Using Boost_$VERSION

if test ! -e $VERSION
then {
    svn co http://svn.boost.org/svn/boost/tags/release/Boost_$VERSION $VERSION
}
fi

#cp -v ./user-config.jam.iphone $VERSION/user-config.jam
cp -v /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.0.sdk/usr/include/bzlib.h $VERSION/
cp -v /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.0.sdk/usr/include/crt_externs.h $VERSION/
cp -v darwin.jam.iphone $VERSION/tools/build/v2/tools/darwin.jam
cd $VERSION

if test ! -e bjam
then {
    echo Create build tools
    cd tools/jam
    ./build_dist.sh
    cp -v `ls -d stage/bin.*`/bjam ../..
    cd ../..
}
fi


./bjam --prefix=`pwd`/../boost-iphone toolset=darwin architecture=arm target-os=iphone macosx-version=iphone-3.2 define=_LITTLE_ENDIAN link=static install --without-mpi --without-wave -layout=versioned pch=off \
  && ./bjam --prefix=`pwd`/../boost-iphonesim toolset=darwin architecture=x86 target-os=iphone macosx-version=iphonesim-3.2 link=static install --without-mpi --without-wave -layout=versioned
